quarkus.application.name=quarkus-latency-demo

# GC algorithm is set via JAVA_OPTS in the Dockerfile / docker-compose
# so both G1GC and ZGC images share this same properties file

quarkus.log.level=WARN
quarkus.log.category."io.quarkus".level=INFO

# Prometheus metrics
quarkus.micrometer.export.prometheus.enabled=true
quarkus.micrometer.binder.jvm=true
quarkus.micrometer.binder.http-server.enabled=true

# Health
quarkus.smallrye-health.root-path=/q/health
