quarkus.application.name=quarkus-grpc-demo

# REST on 8080 (default), gRPC on 9000
quarkus.grpc.server.port=9000

# Enable gRPC reflection (lets grpcurl discover services without --proto flag)
quarkus.grpc.server.enable-reflection-service=true

# Logging — show startup time clearly
quarkus.log.console.format=%d{HH:mm:ss} %-5p [%c{1.}] %s%e%n
quarkus.log.level=WARN
quarkus.log.category."io.quarkus".level=INFO
