apiVersion: 1
datasources:
  - name: JVM Metrics (Prometheus)
    type: prometheus
    uid: ext-prometheus
    # Standalone prom/prometheus container on the observability network
    url: http://prometheus:9090
    access: proxy
    isDefault: false
    editable: false
    jsonData:
      timeInterval: "5s"
